# nginx proxy address - http://172.17.0.1:8103

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  caddy:
    image: caddy:latest
    container_name: caddy-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - caddy
    ports:
      - "8103:80"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./rootfs/config/caddy:/config
      - ./rootfs/data/caddy:/data

networks:
  caddy:
    external: false
